# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(100, 90, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label1.setFont(font)
        self.label1.setObjectName("label1")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menu_Main_Menu = QtWidgets.QMenu(self.menubar)
        self.menu_Main_Menu.setObjectName("menu_Main_Menu")
        self.menu_New = QtWidgets.QMenu(self.menu_Main_Menu)
        self.menu_New.setObjectName("menu_New")
        self.menu_Sub_Menu = QtWidgets.QMenu(self.menubar)
        self.menu_Sub_Menu.setObjectName("menu_Sub_Menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_Open = QtWidgets.QAction(MainWindow)
        self.action_Open.setObjectName("action_Open")
        self.action_Recent = QtWidgets.QAction(MainWindow)
        self.action_Recent.setObjectName("action_Recent")
        self.action_Exit = QtWidgets.QAction(MainWindow)
        self.action_Exit.setObjectName("action_Exit")
        self.actionFile = QtWidgets.QAction(MainWindow)
        self.actionFile.setObjectName("actionFile")
        self.actionProject = QtWidgets.QAction(MainWindow)
        self.actionProject.setObjectName("actionProject")
        self.menu_New.addAction(self.actionFile)
        self.menu_New.addAction(self.actionProject)
        self.menu_Main_Menu.addSeparator()
        self.menu_Main_Menu.addAction(self.menu_New.menuAction())
        self.menu_Main_Menu.addAction(self.action_Open)
        self.menu_Main_Menu.addAction(self.action_Recent)
        self.menu_Main_Menu.addAction(self.action_Exit)
        self.menubar.addAction(self.menu_Main_Menu.menuAction())
        self.menubar.addAction(self.menu_Sub_Menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label1.setText(_translate("MainWindow", "TextLabel1"))
        self.menu_Main_Menu.setTitle(_translate("MainWindow", "&Main Menu"))
        self.menu_New.setStatusTip(_translate("MainWindow", "Create a new file"))
        self.menu_New.setTitle(_translate("MainWindow", "&New..."))
        self.menu_Sub_Menu.setTitle(_translate("MainWindow", "&Sub Menu"))
        self.action_Open.setText(_translate("MainWindow", "&Open"))
        self.action_Recent.setText(_translate("MainWindow", "&Recent"))
        self.action_Exit.setText(_translate("MainWindow", "&Exit"))
        self.actionFile.setText(_translate("MainWindow", "File"))
        self.actionFile.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionProject.setText(_translate("MainWindow", "Project"))

    def clicked(self, text):
        self.label1.setText('clicked')


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
